import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import type { AssistantMessage, Context, SimpleStreamOptions } from "@step-harness/providers";
import { fauxAssistantMessage, fauxToolCall } from "@step-harness/providers";
import { streamSimple } from "@step-harness/providers/compat";
import { afterEach, expect, it, vi } from "vitest";
import { estimateContextTokens } from "../../../src/core/compaction/compaction.ts";
import { SUMMARIZATION_SYSTEM_PROMPT } from "../../../src/core/compaction/utils.ts";
import { createHarness, getMessageText, type Harness } from "../harness.ts";

const SYSTEM_SHA256 = "7f4677db342c3991df3ed0ba729c514db1772ef7af4c39155d2a0d87d08b12bb";
const TEMPLATE_SHA256 = {
	history: "4379f7f63f9fbd36f3f273e94b9566d78967e2e938e4b483957bf67266490572",
	prefix: "0a355395dcd867cb08c3be3229d31475b3a468c51021489fcca4fab6c967cdb6",
	update: "90546e9b55c76b8ac2570b98b0d2849cb3808f102097f52f643b00253edbb333",
};
const GOAL = "SYNTHETIC_GOAL: preserve the parser API and finish the existing plan.";
const ZERO_USAGE = {
	input: 0,
	output: 0,
	cacheRead: 0,
	cacheWrite: 0,
	totalTokens: 0,
	cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 },
};

type RequestKind = "main" | keyof typeof TEMPLATE_SHA256;
interface CapturedRequest {
	kind: RequestKind;
	body: Record<string, unknown>;
	options: Pick<SimpleStreamOptions, "reasoning" | "maxTokens" | "cacheRetention" | "sessionId">;
}

let harness: Harness | undefined;
afterEach(() => {
	harness?.cleanup();
	harness = undefined;
	vi.restoreAllMocks();
	vi.unstubAllGlobals();
});

it("keeps Harbor adaptive main and compaction wire budgets separate without a thinking override", async () => {
	// Generated by Harbor StepHarness._build_model_config() with adaptive and
	// openai-chat. In particular, reasoning and compat are absent, not overridden.
	const modelsJson = JSON.parse(
		readFileSync(fileURLToPath(new URL("../../fixtures/compaction-adaptive-models.json", import.meta.url)), "utf8"),
	) as Record<string, unknown>;
	const h = await createHarness({
		modelsJson,
		settings: {
			compaction: { enabled: true, reserveTokens: 851968, keepRecentTokens: 20000 },
			retry: { enabled: false },
		},
	});
	harness = h;
	await h.authStorage.modify("openai", async () => ({ type: "api_key", key: "offline-fixture-key" }));
	const model = h.session.modelRuntime.getModel("openai", "harbor-adaptive-fixture");
	expect(model).toMatchObject({
		api: "openai-completions",
		reasoning: false,
		contextWindow: 1048576,
		maxTokens: 65536,
	});
	if (!model) throw new Error("Harbor adaptive fixture model was not loaded");
	expect(model.compat).toBeUndefined();
	expect(h.settingsManager.getDefaultThinkingLevel()).toBeUndefined();
	// The normal model-switch path clamps the CLI default to model capabilities.
	// There is no explicit setThinkingLevel("off") or defaultThinkingLevel setting.
	await h.session.setModel(model);
	expect(h.session.thinkingLevel).toBe("off");

	vi.stubGlobal("fetch", () => {
		throw new Error("All HTTP must use the offline serialization interceptor");
	});
	const requests: CapturedRequest[] = [];
	const productionStream = h.session.agent.streamFunction;
	h.session.agent.streamFunction = (requestModel, context, options) => {
		let kind: RequestKind = "main";
		if (context.systemPrompt === SUMMARIZATION_SYSTEM_PROMPT) {
			const text = getMessageText(context.messages[0]);
			// Controlled synthetic input: extract the generated static instruction
			// suffix to pin it. External auditing must also check the system hash,
			// message shape, exact suffix and framing (docs/compaction-integrity.md).
			let suffix = text.slice(text.lastIndexOf("\n</conversation>\n\n") + "\n</conversation>\n\n".length);
			if (suffix.startsWith("<previous-summary>\n")) {
				kind = "update";
				suffix = suffix.slice(suffix.lastIndexOf("\n</previous-summary>\n\n") + "\n</previous-summary>\n\n".length);
			} else {
				kind = suffix.startsWith("The messages above are the PREFIX") ? "prefix" : "history";
			}
			expect(createHash("sha256").update(suffix, "utf8").digest("hex")).toBe(TEMPLATE_SHA256[kind]);
			expect(Object.hasOwn(options ?? {}, "reasoning")).toBe(false);
			expect(context.tools).toBeUndefined();
		}
		const fetch: typeof globalThis.fetch = async (input, init) => {
			const url = input instanceof Request ? input.url : String(input);
			expect(url).toBe("https://compact-study.invalid/v1/chat/completions");
			const raw = input instanceof Request ? await input.clone().text() : String(init?.body);
			const body = JSON.parse(raw) as Record<string, unknown>;
			requests.push({
				kind,
				body,
				options: {
					reasoning: options?.reasoning,
					maxTokens: options?.maxTokens,
					cacheRetention: options?.cacheRetention,
					sessionId: options?.sessionId,
				},
			});
			const response = await streamSimple(h.getModel(), context, { ...options, cacheRetention: "none" }).result();
			if (response.stopReason !== "stop") throw new Error(response.errorMessage ?? "Unexpected faux stop reason");
			const content = getMessageText(response);
			const common = {
				id: `offline-${requests.length}`,
				object: "chat.completion.chunk",
				created: 1,
				model: model.id,
			};
			const chunks = [
				{ ...common, choices: [{ index: 0, delta: { role: "assistant", content }, finish_reason: null }] },
				{
					...common,
					choices: [{ index: 0, delta: {}, finish_reason: "stop" }],
					usage: {
						prompt_tokens: Math.ceil(JSON.stringify(body.messages).length / 4),
						completion_tokens: Math.ceil(content.length / 4),
					},
				},
			];
			return new Response(
				`${chunks.map((chunk) => `data: ${JSON.stringify(chunk)}\n\n`).join("")}data: [DONE]\n\n`,
				{
					status: 200,
					headers: { "content-type": "text/event-stream" },
				},
			);
		};
		// Keep the resolved model and native API dispatch intact; inject only fetch.
		return productionStream(requestModel, context, { ...options, fetch });
	};

	h.setResponses([fauxAssistantMessage("Ready for synthetic inspection.")]);
	await h.session.prompt(GOAL);
	const sessionId = h.session.sessionId;
	const syntheticAssistant = (content: AssistantMessage["content"]): AssistantMessage => ({
		...fauxAssistantMessage(content, { timestamp: 1 }),
		api: model.api,
		provider: model.provider,
		model: model.id,
		usage: ZERO_USAGE,
	});
	h.sessionManager.appendMessage({ role: "user", content: "Inspect the current synthetic turn.", timestamp: 1 });
	h.sessionManager.appendMessage(
		syntheticAssistant([fauxToolCall("read", { path: "synthetic.log" }, { id: "old-read" })]),
	);
	h.sessionManager.appendMessage({
		role: "toolResult",
		toolCallId: "old-read",
		toolName: "read",
		isError: false,
		content: [{ type: "text", text: "synthetic log row\n".repeat(45000) }],
		timestamp: 1,
	});
	h.sessionManager.appendMessage(syntheticAssistant([{ type: "text", text: "retained evidence\n".repeat(6000) }]));
	h.session.agent.state.messages = h.sessionManager.buildSessionContext().messages;
	expect(estimateContextTokens(h.session.messages).tokens).toBeGreaterThan(196608);
	const historySummary = (context: Context) => {
		expect(JSON.stringify(context.messages)).toContain(GOAL);
		return fauxAssistantMessage(`## User Goal\n${GOAL}\n## Next Actions\nContinue the existing plan.`);
	};
	h.setResponses([
		historySummary,
		fauxAssistantMessage("## Next Actions\nInspect retained evidence and continue."),
		fauxAssistantMessage("Continued after automatic compaction."),
	]);
	await h.session.prompt("Continue the existing task.");
	expect(h.eventsOfType("compaction_end")).toMatchObject([{ reason: "threshold", aborted: false, willRetry: false }]);
	expect(JSON.stringify(h.session.messages)).toContain(GOAL);
	expect(h.session.sessionId).toBe(sessionId);

	h.sessionManager.appendMessage({
		role: "user",
		content: "new retained evidence\n".repeat(5000),
		timestamp: Date.now(),
	});
	h.session.agent.state.messages = h.sessionManager.buildSessionContext().messages;
	h.setResponses([historySummary]);
	await h.session.compact();
	h.setResponses([fauxAssistantMessage("Continued after history update.")]);
	await h.session.prompt("Continue the existing plan.");
	expect(h.getPendingResponseCount()).toBe(0);
	expect(requests.map((request) => request.kind)).toEqual(["main", "history", "prefix", "main", "update", "main"]);
	expect(createHash("sha256").update(SUMMARIZATION_SYSTEM_PROMPT, "utf8").digest("hex")).toBe(SYSTEM_SHA256);

	for (const { kind, body, options } of requests) {
		expect(body.max_completion_tokens).toBe(kind === "main" ? 65536 : 32000);
		expect(Object.hasOwn(body, "max_tokens")).toBe(false);
		for (const field of ["reasoning_effort", "thinking", "reasoning", "enable_thinking", "thinking_token_budget"]) {
			expect(Object.hasOwn(body, field), `${kind}: ${field}`).toBe(false);
		}
		if (kind !== "main") {
			const messages = body.messages as Array<{ role: string; content: unknown }>;
			expect(messages.map((message) => message.role)).toEqual(["system", "user"]);
			expect(createHash("sha256").update(getMessageText(messages[0]), "utf8").digest("hex")).toBe(SYSTEM_SHA256);
			expect(options.cacheRetention).toBe("none");
			expect(Object.hasOwn(body, "tools")).toBe(false);
		}
	}
	// Optional audit output is test-only; normal suite runs write no evidence files.
	const evidenceDir = process.env.COMPACT_FIX_EVIDENCE;
	if (evidenceDir) writeFileSync(join(evidenceDir, "adaptive-wire-requests.json"), JSON.stringify(requests, null, 2));
});
