"""Encode the approved PNG/GIF without resampling. Requires Pillow.

Run from any directory; --check verifies assets and the checked-in TS table.
Transparent RGB values are ignored, but alpha must be binary.
"""
import argparse
import json
import re
from pathlib import Path

from PIL import Image, ImageSequence

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "apps/cli/assets/pelican-bike"
OUT = ROOT / "apps/cli/src/ui/view/chrome/step-logo-sprite.generated.ts"
PALETTE = ["#aa91f0", "#f4d56b", "#242132", "#fff6dc"]
COLORS = [tuple(bytes.fromhex(color[1:])) for color in PALETTE]


def encode(image):
    assert image.size == (20, 18), f"Unexpected source size: {image.size}"
    indices = []
    for r, g, b, alpha in (image.getpixel((x, y)) for y in range(18) for x in range(20)):
        assert alpha in (0, 255), "Partial alpha cannot be encoded losslessly"
        indices.append(0 if alpha == 0 else COLORS.index((r, g, b)) + 1)
    rows = [
        "".join(format(indices[yy * 20 + x], "x") for x in range(20) for yy in (y, y + 1))
        for y in range(0, 18, 2)
    ]
    # Independently unpack the terminal rows back to RGBA and check every pixel.
    for y in range(18):
        for x in range(20):
            index = int(rows[y // 2][2 * x + y % 2], 16)
            actual = (*COLORS[index - 1], 255) if index else (0, 0, 0, 0)
            source = image.getpixel((x, y))
            assert actual == (source if source[3] else (0, 0, 0, 0))
    return rows


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    with Image.open(ART / "pedal-20x18.gif") as gif:
        frames, durations = [], []
        for frame in ImageSequence.Iterator(gif):
            frames.append(encode(frame.convert("RGBA")))
            durations.append(frame.info["duration"])
    with Image.open(ART / "logo-20x18.png") as png:
        static = encode(png.convert("RGBA"))
    assert len(frames) == 8 and durations == [140] * 8
    assert frames[0] == static, "The intro must start on the approved static art"
    frame_lines = ",\n".join(
        "\t[\n" + "".join(f'\t\t"{row}",\n' for row in frame) + "\t]" for frame in frames
    )
    static_lines = "".join(f'\t"{row}",\n' for row in static)
    content = f'''/**
 * GENERATED by scripts/generate-pelican-logo.py — do not edit by hand.
 * Source: apps/cli/assets/pelican-bike (approved 20x18 PNG and GIF).
 * No resizing, filtering, palette snapping, or filled transparent holes.
 * Each row pairs source pixels as (upper, lower) hex digits per column.
 * 0 = transparent; 1..N = one-based BIRD_SPRITE_PALETTE index.
 * step-logo.ts preserves both colors with foreground/background half-blocks.
 */

export const BIRD_SPRITE_COLUMNS = 20;
export const BIRD_SPRITE_ROWS = 9;

/** Original artwork colors, not UI theme tokens. */
export const BIRD_SPRITE_PALETTE: readonly string[] = {json.dumps(PALETTE)};

export const BIRD_SPRITE_FRAME_DURATIONS_MS: readonly number[] = {json.dumps(durations)};

export const BIRD_SPRITE_FRAMES: readonly (readonly string[])[] = [
{frame_lines},
];

/** Approved PNG, not the last animation frame. */
export const BIRD_SPRITE_STATIC: readonly string[] = [
{static_lines}];
'''
    if args.check:
        # Ignore formatting only; all data and comments must match regeneration.
        assert re.sub(r"\s+", "", OUT.read_text()) == re.sub(r"\s+", "", content), "Regenerate the sprite table"
        print("PASS: 8 GIF frames + static PNG, all 3240 pixels lossless; TS table current")
    else:
        OUT.write_text(content)
        print(f"Wrote {OUT}: 20x9 cells, 8 frames, 1120ms")


if __name__ == "__main__":
    main()
